---
abstract: 'Helios::Job subclass using JSON to specify job arguments'
author:
  - 'Andrew Johnson <lajandy at cpan dot org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.120351'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HeliosX-Job-JSON
no_index:
  directory:
    - t
    - inc
requires:
  Helios: 2.8
  JSON::Tiny: 0.49
resources:
  repository: git://github.com/logicalhelion/heliosx-job-json.git
version: 0.02_3670
